### ISSUE TITLE
Output content to a HTML webpage instead of to Terminal

### ISSUE THREAD

**Issue by VerisimilitudeX** [VerisimilitudeX/DNAnalyzer#17]

**Comment by charlygg** [comment]
Can you specify please more information about this requirement? Also, I can help with this

**Comment by Verisimilitude11** [comment]
Hi @charlygg, thanks for your interest in contributing to the world of open source! Outputting the content of the program to a static web page is something that the developer team will really appreciate. To get started, navigate to our GitHub repository: https://github.com/Verisimilitude11/DNAnalyzer and fork it. Take some time to read the documentation and to acquaint yourself with the code. Thanks again for contributing, we at DNAnalyzer really appreciate your time and help!

**Comment by Verisimilitude11** [comment]
Regarding the requirements for this issue, I actually don't have a strong background in web development. However, @Nv7-GitHub should be able to answer this question pretty well. We'll get back to you within 24 hours. 
However, in a broad sense, we could go about this in 2 ways:
1. The program currently outputs to the Terminal - change this to output to a static web page (use a Servlet container with a template page and just fill in the values outputted by the Java code):
![image](https://user-images.githubusercontent.com/96280466/193187964-07291e3a-297d-4669-a085-c80e40597da0.png)
2. Change all of the code to JavaScript (perhaps we can use a converter online) and create a full-fledged web version of the analyzer

If you have any ideas/suggestions for implementing this, please let us know! Also, if this feels like it would take too much time, feel free to check out some of the easier issues in this project.

**Comment by Verisimilitude11** [comment]
@Nv7-GitHub could you please help us with this?

**Comment by Nv7-GitHub** [comment]
Yeah, the first method would be pretty easily integrated with the existing codebase (just output HTML code instead of formatted text), but the second one would require a lot more code (code an HTTP server). I could implement generating an HTML output file soon though, probably as an option for the output format.

**Comment by Verisimilitude11** [comment]
> Yeah, the first method would be pretty easily integrated with the existing codebase (just output HTML code instead of formatted text), but the second one would require a lot more code (code an HTTP server). I could implement generating an HTML output file soon though, probably as an option for the output format.

Sounds good @Nv7-GitHub. Let's go with option 1 then. I assigned the issue to you.

**Comment by charlygg** [comment]
> Yeah, the first method would be pretty easily integrated with the existing codebase (just output HTML code instead of formatted text), but the second one would require a lot more code (code an HTTP server). I could implement generating an HTML output file soon though, probably as an option for the output format.

Understood, If you are generating the output in HTML, I could integrate some styles (CSS) to the output page (HTML)

**Comment by Verisimilitude11** [comment]
Sounds great! Would it be possible to implement this in both light and dark mode?

**Comment by Verisimilitude11** [comment]
Maybe the website can have information about DNAnalyzer as well (from the README)

**Comment by Nv7-GitHub** [comment]
Actually we could do it how `go tool pprof` does it where it normally outputs to terminal but has an option to host a webserver which returns an HTML page with the data on it

**Comment by Verisimilitude11** [comment]
2 questions:
1. Would something like this be able to be implemented in Java?
2. Would CSS be able to implemented in addition to this?

**Comment by Nv7-GitHub** [comment]
Yeah I´ve made a static HTTP server without any java dependencies before, and CSS could definitely be implemented in the static page to have a dark & light mode.

**Comment by Verisimilitude11** [comment]
Epic. @charlygg does this sound like something you can implement with the help of @Nv7-GitHub and me?

**Comment by charlygg** [comment]
Yes, I can work on the style for the output page, both dark & light mode

**Comment by Verisimilitude11** [comment]
@charlygg any updates?

**Comment by Verisimilitude11** [comment]
@charlygg do you need any help on this?

**Comment by Verisimilitude11** [comment]
@Nv7-GitHub, do you want to get started on this? We can add this as a CLI arg. Let me know if that works (you can take as much time as you want with this issue)!

**Comment by Nv7-GitHub** [comment]
I'll see if I have time

**Comment by Verisimilitude11** [comment]
> I'll see if I have time

Alright, sounds good!

**Comment by LimesKey** [comment]
@Verisimilitude11 Do you want to lay off with this issue as a GUI is being developed?

**Comment by Verisimilitude11** [comment]
> @Verisimilitude11 Do you want to lay off with this issue as a GUI is being developed?

No I think that we should keep it actually since what we could do is develop a front end and use our current code as the backend. This would allow people to upload files to the website and get it analyzed. We would still keep the GUI and actively develop it as more privacy centric users and users wanting more performance could use it. So, we would have a CLI for power users, a GUI for scientists/researchers, and a website for average users who don't know how to download Java and gradle.

**Comment by LimesKey** [comment]
Hosting that would be expensive... you could probably add a queue system. That is a good idea though, makes it very easy for average users to use this.

**Comment by LimesKey** [comment]
I can handle security stuff with Cloudflare, I'm good at that stuff.

**Comment by Verisimilitude11** [comment]
Alright, sounds great!

**Comment by VerisimilitudeX** [comment]
@charlygg are you still interested in this?
