### ISSUE TITLE
Update Video With CLI Usage

### ISSUE THREAD

**Issue by VerisimilitudeX** [VerisimilitudeX/DNAnalyzer#178]
@shubhwip Would you like to work on this?

**Comment by Ni-vik** [comment]
Is this isuue still open? And if it is can you share more information about it?

**Comment by Ni-vik** [comment]
Okay. Please assign me this issue so that I can start working on it..

**Comment by Verisimilitude11** [comment]
Done.

**Comment by Verisimilitude11** [comment]
Thanks for working on this, @zackrhodes86! I would really appreciate it if you would star this repository if you haven't done so yet!

**Comment by LimesKey** [comment]
@Ni-vik, have you started this yet? If not I created a video that might be helpful, it still needs some editing and it might have a small amount of my personal info in the video; but it shows a walk-through of how to set the program up and download JDK and build Gradle.

Let me know what you think, just don't post it anywhere yet. If you are going to edit some things in the video, I suggest using the song "Reborn by Kavinsky" as the background music. I recorded the video in 1440p 60fps, ask me for the uncompressed file. I can also make another video showing some more commands, I just wanted to make this demo video of how to setup the video for noobies.

https://www.youtube.com/watch?v=n0jav8NTWN4

**Comment by Ni-vik** [comment]
@LimesKey great work. @Verisimilitude11 I was not able to work on it. You can assign this one to @LimesKey

**Comment by Verisimilitude11** [comment]
Sounds good @Ni-vik. Make sure to star this repository and work on another issue!

**Comment by Verisimilitude11** [comment]
@LimesKey thanks for the video! I sent a message in the server regarding this.

**Comment by Verisimilitude11** [comment]
@Ni-vik please join our Discord server: https://discord.gg/5ShCNmyp

**Comment by LimesKey** [comment]
Just waiting for @Verisimilitude11 to edit the video I sent.

**Comment by LimesKey** [comment]
To be honest, I don't know all the features of the program in full detail. Perhaps you can show me @Verisimilitude11?
