### ISSUE TITLE
Save the genes found to a new FASTA file

### ISSUE THREAD

**Issue by VerisimilitudeX** [VerisimilitudeX/DNAnalyzer#18]
Save the genes found by the program already to `genes.fa`

**Comment by Verisimilitude11** [comment]
FASTA files are similar to TXT files, help on this issue would be much appreciated!

**Comment by plopez26DPU** [comment]
This seems interesting 🤔

**Comment by Verisimilitude11** [comment]
Yep, let me know if you want to work on it!

**Comment by plopez26DPU** [comment]
Do you have more information you can send me ? I'm not too sure about fasta files or their use. Would be willing to try to work on it , might take me some time though.

**Comment by Verisimilitude11** [comment]
I think that you would need to save it, similar to creating a .txt file, just with a .fa file extension. FASTA files are most commonly used for DNA sequences as they allow for custom headers for analysis. Thinking on par with a .txt file, you would need to first make a header for each piece of data that is outputted by the current program and then put the actual data under those headers. The headers aren't too complicated if you look at a sample file. Feel free to take extra time on this issue - I'll assign it to you.

**Comment by Verisimilitude11** [comment]
@plopez26DPU, not to rush you, but how far are you on this issue? Feel free to take more time, I'm just wondering if you're still interested in this! 😄

**Comment by plopez26DPU** [comment]
> @plopez26DPU, not to rush you, but how far are you on this issue? Feel free to take more time, I'm just wondering if you're still interested in this! 😄  

Yeah! If you need to move forward,  go ahead. I've been battling this cli stuff lol

**Comment by Verisimilitude11** [comment]
No, it's fine, just checking in 😆. Let me know in the server if you face any difficulty with it.

**Comment by Verisimilitude11** [comment]
Hey @plopez26DPU, I'm going to unassign you from this issue for the time being as you're kinda busy with school, which I totally understand! Let me know once you're ready to resume contributing again!
