### ISSUE TITLE
Refactor Properties.isRandomDNA(String)

### ISSUE THREAD

**Issue by VerisimilitudeX** [VerisimilitudeX/DNAnalyzer#182]
I've selected [**Properties.isRandomDNA(String)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/43151e8f70d86b468dc676c3f5e3f1bc7a4bdca3/src/main/java/DNAnalyzer/Properties.java#L145-L160) for refactoring, which is a unit of **12** lines of code and **5** branch points. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Simple Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of branch points (if, for, while, etc.) per unit to 4.
- **Why**❓ 
Keeping the number of branch points low makes units easier to modify and test.
- **How** 🔧 
Split complex units with a high number of branch points into smaller and simpler ones.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by Verisimilitude11** [comment]
Yes, do you want me to assign it to you?

**Comment by sanjeev0210** [comment]
Sure I will look into it

**Comment by sanjeev0210** [comment]
I have observed that there is an exactly same issue with a PR that is rejected [here](https://github.com/Verisimilitude11/DNAnalyzer/pull/97/files/43187353ac4e57867256143fd855644854728bea) why is that so?

**Comment by Verisimilitude11** [comment]
> @Verisimilitude11 I have observed that there is an exactly same issue with a PR that is rejected [here](https://github.com/Verisimilitude11/DNAnalyzer/pull/97/files/43187353ac4e57867256143fd855644854728bea) why is that so?

I don't think that I rejected that PR, for me it shows that it is merged. How far are you on this issue?

**Comment by sanjeev0210** [comment]
Issue #73 is a clone of this issue and that is already done. So does this still need a PR?

**Comment by Verisimilitude11** [comment]
Yes, it does as that PR didn't fix the issue @sanjeev0210. Also, could you please star this repository and join our Discord server (https://discord.gg/5ShCNmyp) to support our mission? Thank you. Do you want me to assign the issue to you?

**Comment by sanjeev0210** [comment]
okay! Will do

**Comment by Verisimilitude11** [comment]
Sounds great!

**Comment by Verisimilitude11** [comment]
@sanjeev0210 how far are you on this issue?

**Comment by sanjeev0210** [comment]
Hello @Verisimilitude11. I'm still looking into it. Will let you know once I'm done.

**Comment by Verisimilitude11** [comment]
Sounds good @sanjeev0210.

**Comment by Verisimilitude11** [comment]
Hi there,

I hope this message finds you well. I noticed that it has been over a month since you last contributed to the DNAnalyzer project, and I wanted to check in with you to see if you are still interested in being a part of the team.

If you are still interested in working on DNAnalyzer, please let me know and we can discuss how you can get re-involved with the project. If you are no longer interested, I understand and will unassign you from the project for now. However, if you change your mind and want to get involved again in the future, please don't hesitate to reach out – I'll be happy to add you back to the team.

Thank you for your previous contributions to DNAnalyzer, and I hope to hear back from you soon.

Best,
@Verisimilitude11

**Comment by Verisimilitude11** [comment]
You're welcome! Thank you for considering contributing to the repository. I understand that you're busy right now, so don't feel any pressure to contribute. Whenever you do have some free time and feel motivated to contribute, we would love to have your input. In the meantime, if you have any questions or need help with anything, feel free to reach out to me.

Best regards,
Piyush Acharya (@Verisimilitude11)

**Comment by xlxs4** [comment]
You can also do things like

```java
"atgc".chars().map(c -> nucleotidePercentage(nucleotideCount.get(c), dna));
```

if you want more DRY code

**Comment by VerisimilitudeX** [comment]
Oh that's a great idea! Would it be possible for you to open a new PR for this real quick? Thanks! (Also I would really appreciate it if you could support us by starring the repository 😀)

**Comment by xlxs4** [comment]
Sure, the code the issue description links to is obsolete, so the change would be
```java
    public static boolean isRandomDNA(final String dna) {
        long[] nucleotideCount = countBasePairs(dna);
        long a = nucleotideCount[BasePairIndex.ADENINE];
        long t = nucleotideCount[BasePairIndex.THYMINE];
        long g = nucleotideCount[BasePairIndex.GUANINE];
        long c = nucleotideCount[BasePairIndex.CYTOSINE];

        LongStream diffs = LongStream.of(
                Math.abs(a - t),
                Math.abs(a - g),
                Math.abs(a - c),
                Math.abs(t - g),
                Math.abs(t - c),
                Math.abs(g - c)
        );

        return diffs.allMatch(diff -> diff <= 2);
    }
 ```

**Comment by xlxs4** [comment]
Sure
