### ISSUE TITLE
Take input from a file, one gene per line

### ISSUE THREAD

**Issue by VerisimilitudeX** [VerisimilitudeX/DNAnalyzer#19]
Remove all occurrences of `\n` in the file, effectively turning this file:
```txt
ATGCTGTCGTCGCTCGTCGCTTCTCGTTTCC
ATATATATATATATATATATATATATATATATATA
GCGCGCGCGCVGGCGCGCCGCGGCGCCG
ATATATATATATATATATATATATATATATATATA
ATATATATATATATATATATATATATATATATATA
```

Into one line:
```txt
ATGCTGTCGTCGCTCGTCGCTTCTCGTTTCCATATATATATATATATATATATATATATATATATAGCGCGCGCGCVGGCGCGCCGCGGCGCCGATAATATATATATATATATATATATATATATATAATATATATATATATATATATATATATATATATATA
```

**Comment by basil08** [comment]
Hi @Verisimilitude11 , can you provide more info on this?

**Comment by Verisimilitude11** [comment]
So currently, if you look at the code, DNAnalyzer is only able to read one line of a file. For example, in the following file:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/96280466/193393689-0779e2be-53e2-470e-8e24-e228daf83a2f.png">
Only the first line would get analyzed. Could you please implement a method that can combine files that have multiple lines into a string that has no spaces while preserving the original characters? Let me know if you have any other clarifying questions!

**Comment by Verisimilitude11** [comment]
To get started, navigate to our GitHub repository: https://github.com/Verisimilitude11/DNAnalyzer and fork it. Take some time to read the documentation and to acquaint yourself with the code. After making changes, create a pull request. I usually accept PRs within 12 hours, just in case you do want to be one of the 40,000 that get a t-shirt for Hacktoberfest!

**Comment by prasoonmhwr** [comment]
@Verisimilitude11 if not yet assigned , can you assign it to me?

**Comment by Verisimilitude11** [comment]
@basil08 are you interested in working on this?

**Comment by basil08** [comment]
@Verisimilitude11  Yes, I'm working on this!

**Comment by Verisimilitude11** [comment]
> @Verisimilitude11 if not yet assigned , can you assign it to me?

@prasoonmhwr feel free to work on another issue - we have a ton of them! Thanks for your interest in contributing to DNAnalyzer!

**Comment by Verisimilitude11** [comment]
@basil08 any updates?

**Comment by Verisimilitude11** [comment]
> @Verisimilitude11 if not yet assigned , can you assign it to me?

@prasoonmhwr are you still interested in working on this issue?

**Comment by Verisimilitude11** [comment]
Could you also please star this repository to show you support for our mission @prasoonmhwr @basil08? Thanks!

**Comment by Verisimilitude11** [comment]
@prasoonmhwr, how far are you on this issue?

**Comment by Verisimilitude11** [comment]
@prasoonmhwr and @basil08 are you still interested in working on this project?
