### ISSUE TITLE
Simplify README to make it easier to understand

### ISSUE THREAD

**Issue by VerisimilitudeX** [VerisimilitudeX/DNAnalyzer#195]
Borrow elements from https://github.com/files-community/Files/blob/main/README.md

**Comment by JainSamyak8840** [comment]
I wanted to work on this.

**Comment by Verisimilitude11** [comment]
Sure, I assigned it to you.

**Comment by plopez26DPU** [comment]
Any update on this? Willing to take over if needed

**Comment by Verisimilitude11** [comment]
@JainSamyak8840 I would really appreciate it if you would star this repository if you haven't done so yet!

**Comment by Verisimilitude11** [comment]
@sb-decoder would you like to join our Discord server: https://discord.gg/5ShCNmyp

**Comment by Verisimilitude11** [comment]
@plopez26DPU I assigned the issue to you.

**Comment by sb-decoder** [comment]
> @sb-decoder would you like to join our Discord server: https://discord.gg/5ShCNmyp

Yeah joined!
