### ISSUE TITLE
Detect Circular DNA

### ISSUE THREAD

**Issue by VerisimilitudeX** [VerisimilitudeX/DNAnalyzer#204]

**Comment by plopez26DPU** [comment]
Could you explain more of this please

**Comment by Verisimilitude11** [comment]
We can perhaps implement a Java version of https://github.com/iprada/Circle-Map. However, we'd still have to conduct some research on how circular DNA works. @LimesKey, perhaps you can help with this if you get some time.

**Comment by LimesKey** [comment]
I'll get back to you on that, I'm still researching.

**Comment by Verisimilitude11** [comment]
Got it, no rush
