### ISSUE TITLE
Randomness Rating Percentage Tolerance Configuration

### ISSUE THREAD

**Issue by LimesKey** [VerisimilitudeX/DNAnalyzer#229]
This would be a feature in the config file to set how much tolerance you would have for the program to detect a string of DNA as random. In some instances, the machine learning algorithm can only predict new information based on past experiences, but if the DNA it was given was completely random it could give a completely false report of the DNA. 

Some people will give the program DNA that may seem as random or garbage but that actually is real and not random strings of DNA. There could be a calibrated default value for the tolerance but people have the ability to have a higher or lower percentage. A higher percentage randomness tolerance could mean that the program will detect the DNA as more likely to be random. A lower percentage will make the program less likely to detect the DNA as random. 

Maybe some people here can first find a good default tolerance rating for this and also include some real-world data. Genes are a complicated thing to predict accurately because of epigenetics and many other factors, which is why the probability scale may come in handy.

**Comment by LimesKey** [comment]
Too in-specific

**Comment by Verisimilitude11** [comment]
Since we're planning on incorporating machine learning in DNAnalyzer, I was thinking that we could use it to fine tune the randomness tolerance percentage from its base case right now. @LimesKey thoughts?

**Comment by LimesKey** [comment]
@Verisimilitude11 That sounds good but it might be overkill for what we want to accomplish. I would have to get a third party to confirm with. Let me try asking ChatGPT what it thinks!

**Comment by LimesKey** [comment]
@Verisimilitude11 

> It is possible to use machine learning to determine whether a text file is random or not. However, it may not necessarily be the best approach, as there are other methods that could potentially be more effective and efficient.
>
>One approach you could consider is to use statistical tests for randomness. These tests are designed to measure the degree to which a sequence of data points conforms to a random distribution. If the sequence exhibits characteristics that are significantly different from a random distribution, it is likely not random. There are a variety of statistical tests that can be used for this purpose, such as the Chi-squared test, the Kolmogorov-Smirnov test, and the G-test.
>
>Another approach you could consider is to use a simple heuristic to determine whether the text file is random. For example, you could count the number of times each character appears in the file, and if the distribution of characters is fairly uniform, it could be an indication that the text is random. You could also consider using other heuristics, such as the length of the words in the text or the frequency of certain common words or phrases.
>
>Ultimately, the best approach will depend on your specific needs and the characteristics of the text you are analyzing. It may be worth considering a combination of approaches, such as using statistical tests to confirm the results of a simple heuristic.


We should get a heuristic analyst.

**Comment by Verisimilitude11** [comment]
That's a good point. I must say, I'm pleasantly surprised that our AI overlords are willing to lend their expertise to the humble task of determining randomness in text files! In all seriousness though, since you have the most experience with Discord (you practically live on that platform, don't you?), do you know any good servers where we can ask for help regarding this? Or should we just set up camp in a random server and hope for the best?

**Comment by LimesKey** [comment]
This would be more of a programming-related question, so the best bet for discord would be to ask this question in the Python discord or Java help discord server. But since this question is long and would require a lengthy response, the best way would be through creating a post on Reddit. For Reddit, I don't know many subreddits that would be useful for this question but r/MLQuestions, r/learnmachinelearning are good; if we are using Rust to code this specific feature, r/rust would also be good. Discord is better for simpler, shorter and fast responses to questions whilst Reddit is better for longer more information-rich help.

🤣 , might as well ask the AI to solve all the issues and feature requests for me!

**Comment by Verisimilitude11** [comment]
Got it, that sounds like a good idea. I don't have a Reddit account yet, but I can help you craft a post once I return from vacation. Wow, it looks like you have 2 houses, Discord and now Reddit 😆

Oh also, I found a pretty interesting repository for ChatGPT prompts that you might like: https://github.com/f/awesome-chatgpt-prompts
