### ISSUE TITLE
CLI Not Reporting Version Correctly

### ISSUE THREAD

**Issue by plopez26DPU** [VerisimilitudeX/DNAnalyzer#245]
**Describe the bug**
When using the CLI argument for displaying version, only displays a new line with no version information being displayed.

**To Reproduce**

type `java -jar build/libs/DNAnalyzer.jar -V` into terminal

**Expected behavior**
The up-to-date version of DNAnalyzer should be displayed. 

**Screenshots**

<img width="873" alt="image" src="https://user-images.githubusercontent.com/90722929/197421846-e1aab9c3-bf79-4044-a1ee-6d3a93e3b118.png">

**Desktop (please complete the following information):**

- OS: Windows
- Version 2

**Comment by plopez26DPU** [comment]
Assign me this too

**Comment by Verisimilitude11** [comment]
Sounds good @plopez26DPU.

**Comment by plopez26DPU** [comment]
@Verisimilitude11 , do you have a file that holds the version changes right now or no?

**Comment by Verisimilitude11** [comment]
Not yet...

**Comment by Verisimilitude11** [comment]
Could you please open another issue for that? Thanks!

**Comment by Verisimilitude11** [comment]
@plopez26DPU, did you resolve this issue?

**Comment by plopez26DPU** [comment]
I started working on a new argument passing, going to get on it again tomorrow

**Comment by Verisimilitude11** [comment]
Hey @plopez26DPU, I'm going to unassign you from this issue for the time being as you're kinda busy with school, which I totally understand! Let me know once you're ready to resume contributing again!
