### ISSUE TITLE
New Animated DNAnalyzer Logo

### ISSUE THREAD

**Issue by CoderAayush2104** [VerisimilitudeX/DNAnalyzer#248]
Please assign this to me.I will do it for you.

**Comment by Verisimilitude11** [comment]
Sure. Could you have an animation with two helixes (the things piece that makes up the `A` in the current DNAnalyzer logo
<img width="32" alt="image" src="https://user-images.githubusercontent.com/96280466/197452369-0fb01d6c-d77d-4b3c-9f0a-a8de5562a564.png">
) on either side of a `D`? The frames would look something like this:
1. {}
2. { }
3. {D}

Let me know if you have any further questions.

**Comment by CoderAayush2104** [comment]
I will try my best to bring the changes.

**Comment by Verisimilitude11** [comment]
Sounds good. I'll approve/give feedback to your PR within 24 hours of your submission. Thanks for working on this! If you haven't already, could you please star this repository? I would really appreciate it.

**Comment by Verisimilitude11** [comment]
@CoderAayush2104, how far are you on this? Feel free to take more time on this if you want to.

**Comment by CoderAayush2104** [comment]
I will not be able to do it . I am unable to put the helix animation . Sorry for the inconvenience.

**Comment by Verisimilitude11** [comment]
No worries, do you want to work on this issue instead: https://github.com/Verisimilitude11/DNAnalyzer/issues/271. In any case, to support our mission, please star this repository and join our Discord server: https://discord.gg/X3YCvGf2Ug. Thank you so much, I really appreciate it!

**Comment by Verisimilitude11** [comment]
@CoderAayush2104 do you think that you can make a new logo for DNAnalyzer under any specification of your choosing? We would really appreciate your help on this! Thank you.
