### ISSUE TITLE
Publish Gradle Package

### ISSUE THREAD

**Issue by VerisimilitudeX** [VerisimilitudeX/DNAnalyzer#252]
This software is already packaged using Gradle, this issue would publish it to GitHub Packages for easier download by users: https://github.com/Verisimilitude11/DNAnalyzer/packages

**Comment by LimesKey** [comment]
@Verisimilitude11 Can you elaborate?

**Comment by Verisimilitude11** [comment]
Updated

**Comment by Verisimilitude11** [comment]
@jaybob007 could you please help me publish the Gradle package to GitHub Packages? I haven't worked with it before. Thanks.

**Comment by Verisimilitude11** [comment]
@jaybob007 could you please help with publishing the package in the Discord server? Thanks!
