### ISSUE TITLE
Design `Current Version` Documentation

### ISSUE THREAD

**Issue by plopez26DPU** [VerisimilitudeX/DNAnalyzer#258]
**Is your feature request related to a problem? Please describe.**
We need a documentation file to display current version of the application. This will also be used with the CLI argument for version identification.

**Describe the solution you'd like**
Either some form of version control [like this](https://rebelsguidetopm.com/how-to-do-document-version-control/) or a basic file with the current version.

**Comment by plopez26DPU** [comment]
Assign me this :)

**Comment by Verisimilitude11** [comment]
Alright, sounds great!

**Comment by Verisimilitude11** [comment]
@plopez26DPU, not to rush you, but how far are you on this issue? Feel free to take more time, just checking in.

**Comment by plopez26DPU** [comment]
@Verisimilitude11 , been moving slow lately. Work and school stealing my free time 😔

**Comment by Verisimilitude11** [comment]
Hey @plopez26DPU, I'm going to unassign you from this issue for the time being as you're kinda busy with school, which I totally understand! Let me know once you're ready to resume contributing again!

**Comment by plopez26DPU** [comment]
> @plopez26DPU how's it going?

Not too bad. You know how life is, started a new job and finishing school. How are you?
