### ISSUE TITLE
Change Web Page Design

### ISSUE THREAD

**Issue by TheParmak** [VerisimilitudeX/DNAnalyzer#269]
The current website (https://www.dnanalyzer.live/) could use a lot of improvement, perhaps some more interactive elements, along with a section on how to support the repo. Too much whitespace too. I would recommend switching to a JS library, preferably React.js or SvelteKit.

**Comment by LimesKey** [comment]
The website could use some improvement, perhaps some more interactive elements along with a section on how to support the repo. Too much whitespace too.

**Comment by LimesKey** [comment]
I really like the modern look and layout of this website, but it might be way too complicated for developers to do. 
https://solana.com/
@TheParmak wants to do https://kuon.space/ but I don't like it as much.

**Comment by Verisimilitude11** [comment]
@TheParmak and @LimesKey , how far are you guys on this issue?

**Comment by TheParmak** [comment]
As far as I can spend time on it which is none currently:/

**Comment by Verisimilitude11** [comment]
Alright, no worries. Do you have an estimated timeline on when you can get it done by?

**Comment by TheParmak** [comment]
Well, I don't really know honestly. All I can say I "should" be free in not more than 20 days but 🤷‍♂️

**Comment by TheParmak** [comment]
I'll certainly work on this at the first chance when I have time but having time is kinda hard these days

**Comment by Verisimilitude11** [comment]
> I'll certainly work on this at the first chance when I have time but having time is kinda hard these days

I can relate, don't worry about it. By the way, do you know how to code in Python?

**Comment by TheParmak** [comment]
Yes, I do. Of course.

**Comment by Verisimilitude11** [comment]
@TheParmak how's school going for you?

**Comment by Lyndsayfutrell** [comment]
I'd like to help with the site.

**Comment by Verisimilitude11** [comment]
Sounds good @Lyndsayfutrell! This is one of our most prioritized issues so we really appreciate your help on this.

**Comment by Lyndsayfutrell** [comment]
![Screen Shot 2023-01-28 at 4 16 56 PM](https://user-images.githubusercontent.com/110249537/215292321-89269f48-4f9c-4056-b173-e0c76530c152.png)

Here's where I am at so for making the react page. I did adjust the buttons to make them smaller. Definitely need help from someone who's good at svg/animating to fix the DNA and make some cool effects.
