### ISSUE TITLE
Add more detailed documentation and tutorials to DNAnalyzer

### ISSUE THREAD

**Issue by VerisimilitudeX** [VerisimilitudeX/DNAnalyzer#328]
DNAnalyzer should include more detailed documentation and tutorials to help users better understand how to use the software and get the most out of it. This could include in-depth explanations of the different features and tools available in DNAnalyzer, as well as step-by-step guides for performing common tasks. Improved documentation would make it easier for new users to get started with DNAnalyzer and for experienced users to explore its full capabilities.

**Comment by LimesKey** [comment]
I will do the tutorial part as a youtube video

**Comment by Verisimilitude11** [comment]
Sounds good! I'm going to make a channel for DNAnalyzer, although I might just rename my personal account. I'll get you access to that so you can add the video there.

**Comment by LimesKey** [comment]
I will wait till #337 is fixed and when #339 is merged

**Comment by Verisimilitude11** [comment]
Alright, so we're just waiting on #339 then since #337 got fixed.
