### ISSUE TITLE
Add customization options to DNAnalyzer

### ISSUE THREAD

**Issue by VerisimilitudeX** [VerisimilitudeX/DNAnalyzer#331]
DNAnalyzer should include customization options to allow users to tailor the appearance and layout of the software to suit their preferences. This could include the ability to change the color scheme, font size, or other visual elements. Customization options would make DNAnalyzer more personal and user-friendly, and allow users to customize the software to meet their specific needs.

**Comment by collegedude9300** [comment]
Just letting you know, I would like to work on this.

**Comment by Verisimilitude11** [comment]
Alright @collegedude9300, sounds good!

**Comment by Verisimilitude11** [comment]
@collegedude9300, just checking in, how far are you on this issue? Also, could you please star our repository to show your support? Thanks!
