### ISSUE TITLE
(JAVA-W1062) Wrong thread for swing method invocation

### ISSUE THREAD

**Issue by VerisimilitudeX** [VerisimilitudeX/DNAnalyzer#343]
## Description
Methods `show()`, `setVisible()`, and `pack()` must not be invoked on the main thread.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Verisimilitude11/DNAnalyzer/issue/JAVA-W1062/occurrences/](https://deepsource.io/gh/Verisimilitude11/DNAnalyzer/issue/JAVA-W1062/occurrences/)

**Comment by Rishav1707** [comment]
Do you want this to be removed

**Comment by Verisimilitude11** [comment]
@Rishav1707 there's information available in the DeepSource link on how to fix it. Let me know if you need any additional clarifications!
<img width="270" alt="image" src="https://user-images.githubusercontent.com/96280466/211733606-97ecf894-b916-4316-b873-55f4edf8a627.png">

**Comment by VerisimilitudeX** [comment]
@Rishav1707 when will you send your PR?
