### ISSUE TITLE
Explain the role of G-C content accordingly to organism enviroment, evolutionary status and characteristics

### ISSUE THREAD

**Issue by i2kmt** [VerisimilitudeX/DNAnalyzer#405]
After jumping on to @LimesKey 's issue [here](https://github.com/VerisimilitudeX/DNAnalyzer/issues/378) and chatting with him, I suggested using the G-C content information to describe the selected organisms. The role of G-C content in DNA varies and can be:
1) Keeping DNA stable (if the organism lives in a high-temperature environment)
2) Let transcription factors bind on and regulate the genome expression of a specific region.
3) Eucaryotic organisms have G-C-rich regions on their DNA. These regions contain many genes, which relates to the previous point.

I will try to see if there is anything else we could relate the G-C content with. What do you think? @VerisimilitudeX

**Comment by LimesKey** [comment]
The roles of the G-C content in DNA don't seem that useful, would the average G-C content of the entire organism be useful at all? Or would I need the GC content of individual genes?

**Comment by i2kmt** [comment]
Besides keeping the DNA stable in high-temperature environments, I don't think that the average G-C content should show something more. I think individual genes should be better. I propose to choose some orthologous genes among the organisms and compare their G-C content. That way we could see how close or far the organisms are according to an evolutionary path. 
This is the simplest thing that comes to my mind for this subject. We can dig even deeper but I don't think it's necessary.

**Comment by i2kmt** [comment]
Yes, but I don't think we should separate it, we should just find orthologous genes among these organisms. I can start working on it and let you know if it's doable

**Comment by i2kmt** [comment]
I believe there are A LOT of orthologous genes. Most of them will be related to basic cellular or tissue functions. So I'm going to focus on how the basic genes have changed through time

**Comment by VerisimilitudeX** [comment]
Alright @i2kmt, sounds good! Just checking in - how's your research on orthologous genes going? Once you figure out whether we can use it in DNAnalyzer or not, let me know how we could implement it in code. Thanks!

**Comment by VerisimilitudeX** [comment]
Also I saw the work that you're doing for AcubeSAT and it's super cool to see!

**Comment by i2kmt** [comment]
Heyy now it's exam period in my uni so I haven't worked on it. I will be able to do so in 2 weeks. Thank you for appreciating AcubeSAT :)

**Comment by VerisimilitudeX** [comment]
> Heyy now it's exam period in my uni so I haven't worked on it. I will be able to do so in 2 weeks. Thank you for appreciating AcubeSAT :)

No worries, good luck!
