### ISSUE TITLE
https://dnanalyzer.org doesn't load

### ISSUE THREAD

**Issue by maxwofford** [VerisimilitudeX/DNAnalyzer#449]
**Describe the bug**
https://dnanalyzer.org doesn't load

**To Reproduce**

1. Click the URL in the repo description.
2. https://dnanalyzer.org redirects to https://dnanalyzer.org/lander
3. See a blank page

**Expected behavior**
I expect to see the page

**Screenshots**

<img width="1056" alt="Screenshot 2024-07-28 at 05 00 36" src="https://github.com/user-attachments/assets/f2afdadb-9be7-46b2-9b1a-59a0d2d588a3">

**Desktop (please complete the following information):**

- OS: macos 14.5
- Browser safari/arc/chrome

**Comment by VerisimilitudeX** [comment]
Hi @maxwofford, good to see you here. Thank you so much for reporting this issue, I’ll take a look in the morning! For now, the README should cover the important information. The website supports running the program on a server (free), so that’s the only feature missed for now.
