### ISSUE TITLE
Refactor ProteinFinder.getProtein(String,String,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList)

### ISSUE THREAD

**Issue by VerisimilitudeX** [VerisimilitudeX/DNAnalyzer#82]
I've selected [**ProteinFinder.getProtein(String,String,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/5092890e50acec640441254ba5196a045f219f18/src/DNAnalyzer/ProteinFinder.java#L26-L84) for refactoring, which is a unit of **42** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by FireNdIce3** [comment]
Hi there! Can I work on this issue?

**Comment by Verisimilitude11** [comment]
Sure! Let me know if you have any questions.

**Comment by Verisimilitude11** [comment]
To get started, navigate to our GitHub repository: https://github.com/Verisimilitude11/DNAnalyzer and fork it. Take some time to read the documentation and to acquaint yourself with the code. After making changes, create a pull request. I usually accept PRs within 12 hours, just in case you do want to be one of the 40,000 that get a t-shirt for Hacktoberfest!

**Comment by FireNdIce3** [comment]
Okay, thanks!

**Comment by FireNdIce3** [comment]
Hi there. I have a query. Can I use var args in this function to make the code simpler?

**Comment by Verisimilitude11** [comment]
Hello! Could you please clarify/provide an example of what you mean by using var args? Thanks!

**Comment by Verisimilitude11** [comment]
Never mind, I understand what you mean, feel free to use it!

**Comment by Verisimilitude11** [comment]
@FireNdIce3 how far are you on this issue?

**Comment by Verisimilitude11** [comment]
@FireNdIce3 any updates?

**Comment by plopez26DPU** [comment]
I'll work on this too. Might take me some extra time

**Comment by Verisimilitude11** [comment]
Sounds good, no problem.

**Comment by Verisimilitude11** [comment]
Hey @plopez26DPU, I'm going to unassign you from this issue for the time being as you're kinda busy with school, which I totally understand! Let me know once you're ready to resume contributing again!
